nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:8080']
        allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/add-guest/': ~